### ISSUE TITLE
[Feat] API 환경설정, get API

### ISSUE THREAD

**Issue by iiuoon** [whatever-mentoring/AKKIN_iOS#34]
## 💡 Description

네트워크 초기 세팅과 애플로그인을 구현합니다.
## 📝  Progress
- [ ] 네트워크 세팅
- [ ] 애플로그인 구현

**Comment by brorica** [comment]
dummy 유저 토큰 받고 아낀항목 생성, 보기까지 가능한지 확인해주시면 됩니다

주간, 월간 통계도 만들었는데 이쪽은 https 달고 할 거라 아직 배포단엔 없어요

**Comment by iiuoon** [comment]
> dummy 유저 토큰 받고 아낀항목 생성, 보기까지 가능한지 확인해주시면 됩니다
> 
> 주간, 월간 통계도 만들었는데 이쪽은 https 달고 할 거라 아직 배포단엔 없어요

넵넵!
